name: 'exec'
description: 'run sbt testCompilation'
inputs:
  command:  # id of input
    description: 'command to execute'
    required: true
    default: 'echo "hello"'

runs:
  using: 'node12'
  main: 'dist/index.js'
